In [406]:
import numpy as np
import pandas as pd
import sys

In [4]:
from math import exp

class Tanh:

    def transfer(self, activation):
        '''
        Tanh activation function.
        '''
        return (exp(activation) - exp(-activation))/(exp(activation) + exp(-activation))
    
    def transfer_derivative(self, output):
        '''
        We are using the tanh transfer function, the derivative of which can be calculated as follows:
        derivative = 1 - (output * output)
        '''
        return 1 - (output * output)

In [5]:
class Sigmoid:

    def transfer(self, activation):
        '''
        Sigmoid activation function.
        '''
        return 1.0 / (1.0 + exp(-activation * 1.0))
    
    def transfer_derivative(self, output):
        '''
        We are using the sigmoid transfer function, the derivative of which can be calculated as follows:
        derivative = output * (1.0 - output)
        '''
        return output * (1.0 - output)

In [114]:
df=pd.read_csv('dermatology.csv', sep=',',header=None)

In [115]:
df = df[((df[34]==1) | (df[34]==2) | (df[34]==3)) & (df[33]!='?')]
df[34]-=1
dataset = df.values.astype('float') 

In [8]:
mlp = MultilayerNnClassifier()
activationFunction = Sigmoid()

In [83]:
dataset_in = dataset[:,:-1]
dataset_out = dataset[:,-1]

In [84]:
training_rate = 0.5
weights = train_network_main(dataset_in.T, dataset_out.T, training_rate, shape, weights)

/home/satyam/.local/lib/python2.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: overflow encountered in exp
  # This is added back by InteractiveShellApp.init_path()


In [85]:
print weights[1]

[[-9.94086170e+00  6.95203702e+04  6.94707247e+04  6.95106215e+04
   6.94234527e+04  6.95199800e+04  6.94315231e+04  1.60657337e+01
   6.94024972e+04  6.94479523e+04  6.95022502e+04 -4.95368030e+00
   6.92850578e+04  6.93953063e+04  6.93557800e+04  6.94270365e+04
   6.94531880e+04  6.94758623e+04  6.94757342e+04  6.94700239e+04
   6.95051767e+04  6.94396464e+04  6.94989529e+04 -1.04207957e+01
  -3.08198361e+00  6.94016699e+04  6.94885936e+04  6.94106000e+04
   6.93392372e+04  6.95106037e+04 -1.18070331e+01  6.95066854e+04
   6.94493330e+04  1.50730511e+01  6.94948511e+04  6.95107435e+04
   6.95121797e+04  6.95088958e+04  6.94354794e+04  6.94636776e+04]
 [-2.98819154e+00  6.95186699e+04  6.94877299e+04  6.95109310e+04
   6.94042011e+04  6.95050691e+04  6.94488206e+04 -1.00336556e+01
   6.93821393e+04  6.94258984e+04  6.94903314e+04 -1.59839838e+00
   6.92800540e+04  6.93908432e+04  6.93614453e+04  6.94327835e+04
   6.94654591e+04  6.94756133e+04  6.94915735e+04  6.94529525e+04
   6.9488

In [90]:
test_input = dataset_in.T
test_output = run_network(test_input, shape, weights)

(40, 34)
(3, 40)


/home/satyam/.local/lib/python2.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: overflow encountered in exp
  # This is added back by InteractiveShellApp.init_path()


In [91]:
test_output

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [981]:
class NeuralNetwork:
    def __init__(self, inputl, hidden, outputl):
        self.hidden_nodes = hidden
        self.num_features = inputl
        self.num_labels = outputl
        np.random.seed(0)
        self.layer1_weights_array = np.random.normal(0.01, 1, [self.num_features, self.hidden_nodes])
        self.layer1_biases_array = np.zeros((1, self.hidden_nodes))
        self.layer2_weights_array = np.random.normal(0.01, 1, [self.hidden_nodes, self.num_labels])
        self.layer2_biases_array = np.zeros((1, self.num_labels))

    def relu_activation(self, data_array):
        return np.maximum(data_array, 0)
    
    def softmax(self, output_array):
        logits_exp = np.exp(output_array.astype(np.float)-np.max(output_array))
        val = logits_exp / np.nansum(logits_exp, axis = 1, keepdims = True)
        val[np.isnan(val)] = 0
        return val
    
    def cross_entropy_softmax_loss_array(self, softmax_probs_array, y_onehot):
        indices = np.argmax(y_onehot, axis = 1).astype(int)
        predicted_probability = softmax_probs_array[np.arange(len(softmax_probs_array)), indices]
        log_preds = np.log(predicted_probability+sys.float_info.epsilon)
        log_preds[np.isnan(log_preds)] = 0
        loss = (-1.0 * np.nansum(log_preds)) / (1.0 * len(log_preds) )
        return loss
    
    def get_labels_in_one_hot_encoding(self, labels):
        labels_onehot = np.zeros((labels.shape[0], self.num_labels)).astype(int)
        labels_onehot[np.arange(len(labels)), labels.astype(int)] = 1
        return labels_onehot
    

    def regularization_L2_softmax_loss(self, reg_lambda, weight1, weight2):
        weight1_loss = 0.5 * reg_lambda * np.nansum(weight1 * weight1)
        weight2_loss = 0.5 * reg_lambda * np.nansum(weight2 * weight2)
        return weight1_loss + weight2_loss
    
    
    def train(self, data, labels, reg_lambda, learning_rate):
        pr_loss = 0
        delta_loss = 100
        loss = 100
        delta = 0.0001
        step = 0
        while loss>delta and delta_loss>0.01* delta:
            input_layer = np.dot(data, self.layer1_weights_array)
            hidden_layer = self.relu_activation(input_layer + self.layer1_biases_array)
            output_layer = np.dot(hidden_layer, self.layer2_weights_array) + self.layer2_biases_array
            output_probs = self.softmax(output_layer)
            loss = self.cross_entropy_softmax_loss_array(output_probs, labels)
            loss += self.regularization_L2_softmax_loss(reg_lambda, self.layer1_weights_array, self.layer2_weights_array)

            output_error_signal = (output_probs - labels) / output_probs.shape[0]

            error_signal_hidden = np.dot(output_error_signal, self.layer2_weights_array.T) 
            error_signal_hidden[hidden_layer <= 0] = 0

            gradient_layer2_weights = np.dot(hidden_layer.T, output_error_signal)
            gradient_layer2_bias = np.sum(output_error_signal, axis = 0, keepdims = True)

            gradient_layer1_weights = np.dot(data.T, error_signal_hidden)
            gradient_layer1_bias = np.sum(error_signal_hidden, axis = 0, keepdims = True)

            gradient_layer2_weights += reg_lambda * self.layer2_weights_array
            gradient_layer1_weights += reg_lambda * self.layer1_weights_array

            self.layer1_weights_array -= learning_rate * gradient_layer1_weights
            self.layer1_biases_array -= learning_rate * gradient_layer1_bias
            self.layer2_weights_array -= learning_rate * gradient_layer2_weights
            self.layer2_biases_array -= learning_rate * gradient_layer2_bias
            delta_loss = abs(loss-pr_loss)
            pr_loss = loss
            if step % 500 == 0:
                    print 'Loss at step {0}: {1}'.format(step, loss)
            step += 1

    def predict(self, test_dataset, test_labels):
        input_layer = np.dot(test_dataset, self.layer1_weights_array)
        hidden_layer = self.relu_activation(input_layer + self.layer1_biases_array)
        scores = np.dot(hidden_layer, self.layer2_weights_array) + self.layer2_biases_array
        probs = self.softmax(scores)
        print self.accuracy(probs, test_labels)
        
    def accuracy(self, predictions, labels):
        preds_correct_boolean =  np.argmax(predictions, 1) == np.argmax(labels, 1)
        correct_predictions = np.sum(preds_correct_boolean)
        accuracy = (100.0 * correct_predictions) / predictions.shape[0]
        return accuracy


In [984]:
network = NeuralNetwork(34,4,3)

In [985]:
network.train(dataset_in,labels_onehot,0.1, 0.05)

Loss at step 0: 20.6698861333
Loss at step 500: 1.16486716906
Loss at step 1000: 0.681321762138
Loss at step 1500: 0.463562725132
Loss at step 2000: 0.625790770447
Loss at step 2500: 0.542061464103
Loss at step 3000: 0.594901781216
Loss at step 3500: 0.727963411366
Loss at step 4000: 0.553483144232
Loss at step 4500: 0.816272765552
Loss at step 5000: 0.678383194249
Loss at step 5500: 0.589022736733
Loss at step 6000: 1.78341279891
Loss at step 6500: 0.731774074839
Loss at step 7000: 0.537608421989
Loss at step 7500: 0.699577242802
Loss at step 8000: 0.569415401434
Loss at step 8500: 1.18068698445
Loss at step 9000: 1.21306865478
Loss at step 9500: 0.619158980516
Loss at step 10000: 0.731162293407
Loss at step 10500: 1.07555625911
Loss at step 11000: 0.614275986963
Loss at step 11500: 0.62374465664
Loss at step 12000: 0.627654808342
Loss at step 12500: 0.657768977
Loss at step 13000: 0.698929993165
Loss at step 13500: 0.63717952531
Loss at step 14000: 0.761015479189
Loss at step 14500: 

KeyboardInterrupt: 

In [898]:
labels_onehot = network.get_labels_in_one_hot_encoding(dataset_out)

In [899]:
network.predict(dataset_in, labels_onehot)

[[ 0.58617836  0.12278547  0.35278128  0.49988728]
 [ 0.63855407 -0.36810269  0.34254046 -0.08638118]
 [-0.06254936  0.13329651  0.05441899  0.51330052]
 [ 0.25990555  0.03318686  0.1615898  -0.08843037]
 [ 0.53843244 -0.07552668  0.11483682 -0.23928151]
 [-0.90899405  0.23721108  0.31256802 -0.45686688]
 [ 0.81490039 -0.51688534  0.01993093 -0.05768287]
 [ 0.55146785  0.52879815  0.05896061 -0.04510642]
 [-0.30658312 -0.71173002 -0.12207506  0.44890636]
 [ 0.4525712   0.42292906 -0.13616387  0.30867529]
 [-0.36993281 -0.50564959 -0.60633334  0.76731683]
 [-0.17860113 -0.15301555 -0.44423835  0.08610573]
 [-0.57331476 -0.07463318 -0.31651084  0.06333756]
 [-0.19587171 -0.42762266 -0.00778731  0.2147975 ]
 [ 0.02735115  0.11169337 -0.22316451 -0.13408409]
 [-0.27485297 -0.13659145 -0.28708538 -1.15157536]
 [ 0.0549692  -0.16105787 -0.58042944  0.14020861]
 [-0.31907488  0.01593869  0.26354458  0.19777152]
 [ 0.38025197 -0.45179737  0.14674787 -0.11762539]
 [-0.29786925 -0.21588852 -0.10

In [791]:
for r in dataset_in:
    print r

[ 2.  2.  0.  3.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  3.  2.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  3.  0.  0.  0.  1.  0. 55.]
[3. 3. 3. 2. 1. 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 2. 0. 2. 2. 2. 2. 2. 1.
 0. 0. 0. 0. 0. 0. 0. 1. 0. 8.]
[ 2.  1.  2.  3.  1.  3.  0.  3.  0.  0.  0.  1.  0.  0.  0.  1.  2.  0.
  2.  0.  0.  0.  0.  0.  2.  0.  2.  3.  2.  0.  0.  2.  3. 26.]
[ 2.  2.  2.  0.  0.  0.  0.  0.  3.  2.  0.  0.  0.  3.  0.  0.  2.  0.
  3.  2.  2.  2.  2.  0.  0.  3.  0.  0.  0.  0.  0.  3.  0. 40.]
[ 2.  3.  2.  2.  2.  2.  0.  2.  0.  0.  0.  1.  0.  0.  0.  1.  2.  0.
  0.  0.  0.  0.  0.  0.  2.  2.  3.  2.  3.  0.  0.  2.  3. 45.]
[ 2.  3.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  2.  1.  0.  2.  2.  0.
  2.  0.  0.  0.  1.  0.  0.  0.  0.  2.  0.  0.  0.  1.  0. 41.]
[ 2.  2.  3.  3.  3.  3.  0.  2.  0.  0.  0.  2.  0.  0.  0.  2.  3.  0.
  0.  0.  0.  0.  0.  0.  0.  2.  2.  3.  2.  0.  0.  3.  3. 57.]
[ 3.  3.  2.  1.  1.  0.  0.  0.  2.  2.  1.  0.  0.  0.  0. 

In [792]:
labels_onehot

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1,

In [986]:
from sklearn.model_selection import train_test_split
train_dataset, test_dataset, \
train_labels, test_labels = train_test_split(
    dataset_in, labels_onehot, test_size = .1, random_state=12)

In [987]:
def NN(dataset):
    from sklearn.model_selection import train_test_split
    train_dataset, test_dataset, \
    train_labels, test_labels = train_test_split(
        dataset_in, labels_onehot, test_size = .2, random_state=12)
    network = NeuralNetwork(train_dataset.shape[1],4,train_labels.shape[1])
    network.train(train_dataset,train_labels,0.01, 0.05)
    network.predict(test_dataset, test_labels)

In [988]:
NN(dataset)

Loss at step 0: 13.2506225075
Loss at step 500: 1.5311149643
Loss at step 1000: 1.34450680608
Loss at step 1500: 1.23144821691
Loss at step 2000: 1.59262675034
Loss at step 2500: 0.315126922454
Loss at step 3000: 0.232023580008
Loss at step 3500: 0.205518216
Loss at step 4000: 0.17515667508
100.0


In [989]:
def read_dataset(loc):
    df=pd.read_csv(loc, sep=',',header=None)
    df = df[((df[16]==0) | (df[16]==1) | (df[16]==2) | (df[16]==3))]
    dataset = df.values.astype('float')
    #np.random.shuffle(dataset)
    return dataset
train = read_dataset('pendigits/pendigits.tra')
test = read_dataset('pendigits/pendigits.tes')

In [993]:
train_in = train[:,:-1]
train_out = one_hot_encoding(train[:,-1], 4)
test_in = test[:,:-1]
test_out = one_hot_encoding(test[:,-1],4 )

In [996]:
def NN(train_x, train_y, test_x, test_y, hidden_layer):
    network = NeuralNetwork(train_x.shape[1],hidden_layer,train_y.shape[1])
    network.train(train_x,train_y,0.01, 0.001)
    network.predict(test_x, test_y)
# learning rate: 0.0005 gives 95% accuracy

In [995]:
print test_in.dtype
NN(train_in, train_out, test_in, test_out,10)

float64
Loss at step 0: 27.981513725
Loss at step 500: 1.80987458266
Loss at step 1000: 1.51911303061
Loss at step 1500: 1.78946199782
Loss at step 2000: 1.31729176288
Loss at step 2500: 1.33095732164
92.0112123336


In [922]:
def one_hot_encoding(labels, num_labels):
    labels_onehot = np.zeros((labels.shape[0], num_labels)).astype(int)
    labels_onehot[np.arange(len(labels)), labels.astype(int)] = 1
    return labels_onehot

In [923]:
train_in.dtype

dtype('float64')

/home/satyam/.local/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [409]:
np.log(sys.float_info.epsilon)

-36.04365338911715

In [450]:
dataset.shape

(242, 35)

In [483]:
print train_in.shape

(3058, 16)


In [504]:
print train_in

[[  0.  89.  27. ...   2. 100.   6.]
 [  0.  57.  31. ...  25.  16.   0.]
 [  0.  67.  49. ...  20.  47.   0.]
 ...
 [ 55.  89.  85. ...   0.   0.   3.]
 [ 17.  63.   6. ...  91.   0.  52.]
 [ 59.  65.  91. ...   1. 100.   0.]]


In [925]:
import keras
from keras.optimizers import SGD
from keras.models import Sequential
from keras.layers import Activation, Dropout, Flatten, Dense, LSTM
def NeuralNetwork(XTrain, YTrain, XTest, YTest):
	model = Sequential()
	print np.shape(XTrain)
	print np.shape(YTrain)
	model.add(Dense(16, activation='relu', input_dim=np.shape(XTrain)[1]))
	# model.add(Dense(128, activation='relu'))
	# model.add(Dropout(0.5))
	model.add(Dense(5, activation='relu'))
	model.add(Dropout(0.1))
	model.add(Dense(4, activation='softmax'))
	sgd = SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)
	model.compile(loss='categorical_crossentropy',optimizer=sgd,metrics=['accuracy'])


	x_train=np.array(XTrain)
	x_test=np.array(XTest)
	y_train=np.array(YTrain)
	y_test=np.array(YTest)

	y_train=y_train[:,np.newaxis]
	y_test=y_test[:,np.newaxis]
	mapping = YTrain
	print "len mapping : ",len(mapping)
	print mapping


	y_train=keras.utils.to_categorical(y_train, num_classes=4)
	y_test=keras.utils.to_categorical(y_test, num_classes=4)


	print "len train set",np.shape(x_train),np.shape(y_train)
	print "len test set",np.shape(x_test),np.shape(y_test)
	model.fit(x_train, y_train,epochs=100,batch_size=128,shuffle=True,validation_split=0.25)
	acc= model.evaluate(x_test, y_test, batch_size=128)
	print acc

In [926]:
NeuralNetwork(train_in, train[:,-1], test_in, test[:,-1])

(3058, 16)
(3058,)
len mapping :  3058
[2. 1. 1. ... 3. 0. 1.]
len train set (3058, 16) (3058, 4)
len test set (1427, 16) (1427, 4)
Train on 2293 samples, validate on 765 samples
Epoch 1/100
2293/2293 [==============================] - 0s - loss: 2.7197 - acc: 0.5678 - val_loss: 0.6316 - val_acc: 0.7843
Epoch 2/100
2293/2293 [==============================] - 0s - loss: 0.6049 - acc: 0.7758 - val_loss: 0.3866 - val_acc: 0.8562
Epoch 3/100
2293/2293 [==============================] - 0s - loss: 0.4799 - acc: 0.7985 - val_loss: 0.3131 - val_acc: 0.8797
Epoch 4/100
2293/2293 [==============================] - 0s - loss: 0.4302 - acc: 0.8072 - val_loss: 0.2909 - val_acc: 0.9007
Epoch 5/100
2293/2293 [==============================] - 0s - loss: 0.4132 - acc: 0.8155 - val_loss: 0.2621 - val_acc: 0.9098
Epoch 6/100
2293/2293 [==============================] - 0s - loss: 0.3895 - acc: 0.8373 - val_loss: 0.2480 - val_acc: 0.9137
Epoch 7/100
2293/2293 [==============================] - 0s - los

2293/2293 [==============================] - 0s - loss: 0.1736 - acc: 0.9333 - val_loss: 0.0592 - val_acc: 0.9804
Epoch 65/100
2293/2293 [==============================] - 0s - loss: 0.1721 - acc: 0.9429 - val_loss: 0.0566 - val_acc: 0.9791
Epoch 66/100
2293/2293 [==============================] - ETA: 0s - loss: 0.1735 - acc: 0.921 - 0s - loss: 0.1662 - acc: 0.9376 - val_loss: 0.0577 - val_acc: 0.9804
Epoch 67/100
2293/2293 [==============================] - 0s - loss: 0.1577 - acc: 0.9416 - val_loss: 0.0557 - val_acc: 0.9804
Epoch 68/100
2293/2293 [==============================] - 0s - loss: 0.1647 - acc: 0.9429 - val_loss: 0.0557 - val_acc: 0.9804
Epoch 69/100
2293/2293 [==============================] - 0s - loss: 0.1523 - acc: 0.9411 - val_loss: 0.0557 - val_acc: 0.9804
Epoch 70/100
2293/2293 [==============================] - 0s - loss: 0.1548 - acc: 0.9437 - val_loss: 0.0594 - val_acc: 0.9817
Epoch 71/100
2293/2293 [==============================] - 0s - loss: 0.1693 - acc: 0.9